
name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Connect to VPN
        run: |
          sudo apt-get update
      - name: Prepare VPN config files
        run: |
          echo "${{ secrets.VPN_OVPN }}" | base64 -d > sitst-client.ovpn
          echo "${{ secrets.VPN_CA_CRT }}" | base64 -d > vpn-st_ca.crt
          echo -e "${{ secrets.VPN_USER }}\n${{ secrets.VPN_PASS }}" > vpn-auth.txt
          sudo apt-get install -y openvpn
          sudo openvpn --config sitst-client.ovpn --auth-user-pass vpn-auth.txt --daemon
          sleep 10

      - name: SSH pull and build
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASS }}
          script: |
            cd blog-with-adonis
            git pull origin main
            echo "PATH: $PATH"
            which node || echo 'node not found'
            which npm || echo 'npm not found'
            which git || echo 'git not found'
            node -v || echo 'node -v failed'
            npm -v || echo 'npm -v failed'
            git --version || echo 'git --version failed'
            npm install
            node ace migration:fresh --seed
            npm run build
            cp .env.example .env
            node ace generate:key
            cd build
            cp ../.env .env
            npm ci --omit="dev"
            node bin/server.js
