
name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Connect to VPN
        run: |
          sudo apt-get update
          sudo apt-get install -y openvpn
      - name: Prepare VPN config files
        run: |
          echo "${{ secrets.VPN_OVPN }}" | base64 -d > sitst-client.ovpn
          echo "${{ secrets.VPN_CA_CRT }}" | base64 -d > vpn-st_ca.crt
          echo -e "${{ secrets.VPN_USER }}\n${{ secrets.VPN_PASS }}" > vpn-auth.txt
          sudo openvpn --config sitst-client.ovpn --auth-user-pass vpn-auth.txt --daemon
          sleep 10

      - name: SSH pull and build
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASS }}
          script: |
            if [ ! -d "blog-with-adonis" ]; then
              git clone https://github.com/${{ github.repository }}.git
            fi
            cd blog-with-adonis
            git fetch origin
            git reset --hard origin/main
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            echo "Node path: $(which node)"
            echo "Node version: $(node -v)"
            npm install
            npm run build
            if [ ! -f ".env" ]; then
              cp .env.example .env
              sed -i 's/^NODE_ENV=.*/NODE_ENV=production/' .env
              node ace generate:key
            fi
            cd build
            cp ../.env .env
            npm ci --omit="dev"
            node ace migration:fresh --seed
            npm install -g pm2
            pm2 restart adonis-blog || pm2 start bin/server.js --name adonis-blog
